export const actionTypes = {
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
    SIGN_UP: "SIGN_UP",
    SELECT_QUESTION: "SELECT_QUESTION",
    CREATE_SURVEY:"CREATE_SURVEY",
    ADD_QUESTION: "ADD_QUESTION",
    EDIT_QUESTION : "EDIT_QUESTION",
    ADD_OPTIONS : "ADD_OPTIONS",
    EDIT_OPTIONS : "EDIT_OPTIONS"
};