export const actionTypes = {
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
    SIGN_UP: "SIGN_UP",
    SELECT_QUESTION: "SELECT_QUESTION",
    CREATE_SURVEY:"CREATE_SURVEY",
    ADD_QUESTION: "ADD_QUESTION",
    EDIT_QUESTION : "EDIT_QUESTION",
    ADD_OPTIONS : "ADD_OPTIONS",
    EDIT_OPTIONS : "EDIT_OPTIONS",
    UPDATE_SURVEY : "UPDATE_SURVEY",
    UPDATE_SURVEYRESPONSE : "UPDATE_SURVEYRESPONSE",
    UPDATE_ANSWER : "UPDATE_ANSWER",
    CREATE_SURVEYRESPONSE : "CREATE_SURVEYRESPONSE",
    UPDATE_QUESTIONS_IN_RESPONSE : "UPDATE_QUESTIONS_IN_RESPONSE",
    UPDATE_SURVEYOR_DASHBOARD:"UPDATE_SURVEYOR_DASHBOARD",
    UPDATE_SURVEY_NAME_DATE:"UPDATE_SURVEY_NAME_DATE",
    CHANGE_SURVEY_PUBLISH_STATE:"CHANGE_SURVEY_PUBLISH_STATE"
};